name: Doxygen GitHub Pages Deploy Action

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone doxygen-awesome theme
        run: git clone https://github.com/jothepro/doxygen-awesome-css.git
        shell: bash

      - name: Install Graphviz
        run: sudo apt-get install graphviz -y
        shell: bash

      - uses: actions/checkout@v2

      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag

      - uses: DenverCoder1/doxygen-github-pages-action@v1.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        env:
          RELEASE_VERSION: ${{ steps.get-latest-tag.outputs.tag }}
    env:
      REPO_NAME: ${{ github.event.repository.name }}
      REPO_DESCRIPTION: ${{ github.event.repository.description }}
